name: Or demo
on:
    push:
        branches:
            - main
            - develop
jobs:
    if-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Run this  step if 
              if: github.actor == 'sreemural' || github.actor == 'main'
              run: echo "Running for main branch"

    

